name: Build on Ubuntu
on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: test docker
        run: |
          docker run zephyrprojectrtos/zephyr-build west help<s