# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2


      # Runs a set of commands using the runners shell
      - name: Set up west and project
        run: |
          pip3 install --user -U west
          west init ~/zephyrproject --mr v2.5.0
          cd ~
          wget https://github.com/zephyrproject-rtos/sdk-ng/releases/download/v0.12.4/zephyr-sdk-0.12.4-x86_64-linux-setup.run
          chmod +x zephyr-sdk-0.12.4-x86_64-linux-setup.run
          ./zephyr-sdk-0.12.4-x86_64-linux-setup.run -- -d ~/zephyr-sdk-0.12.4
          cd ~/zephyrproject
          west update
          rsync -rv --exclude=.gitdir $GITHUB_WORKSPACE ~/zephyrproject/project
          

      - name: Build FW
        run: |
          cd ~/zephyrproject/project
          west build project -b nrf52_gyro_klokke
          cp ~/zephyrproject/project/build/zephyr.elf /tmp/nrf52_gyro_klokke.elf

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: /tmp/nrf52_gyro_klokke.elf
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

